kind: Deployment
apiVersion: apps/v1
metadata:
  name : app-deploy
  namespace: notes-app-ns 
  labels:
    app : notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
     app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app-cont
        image: trainwithshubham/notes-app-k8s
        ports:
        - containerPort: 8000
